config/routes.rb
Isitfedoraruby::Application.routes.draw do

  root to: 'home#show'

  get 'contribute', to: 'static_pages#contribute'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'

  get 'searches/suggest_gems' => 'searches#suggest_gems'
  post 'searches/' => 'searches#redirect'
  get 'searches/:id' => 'searches#index'

  resources :fedorarpms, only: [:index, :show] do
    member do
      get :full_deps
      get :full_dependencies
      get :full_dependents
      get :by_owner
      get :badge
      get :not_found
    end
  end

  resources :rubygems, only: [:index, :show]

  resources :stats, only: [:index] do
    get :gemfile_tool, on: :collection
    get :user_rpms
    get :timeline
    get :tljson
    get :user_rpms_data
    post :gemfile_tool, on: :collection
  end

  # unless Rails.application.config.consider_all_requests_local
  get '*not_found', to: 'errors#error_404'
  #  end

end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  def index
    @rpms = FedoraRpm.order('commits desc').limit(10)
    @gems = RubyGem.order('downloads desc').limit(10)
  end

  def user_rpms_data
    @name = params[:stat_id]
    @rpms = FedoraRpm.where('owner LIKE ?', @name)
    respond_to do |format|
      format.json { render json: @rpms.to_json }
    end
  end

  def user_rpms
    @name = params[:stat_id]
    @rpms = FedoraRpm.where('owner LIKE ?', @name)
    @rpms_json = @rpms.to_json
    respond_to do |format|
      format.html
    end
  end

  def timeline
    @stat_id = params[:stat_id]
    respond_to do |format|
      format.html
    end
  end

  def tljson(result = [])
    @stat_id = params[:stat_id]
    @rpm = FedoraRpm.find_by_name(@stat_id)
    @rpm.bugs.each do |bug|
      result << { content: bug.name, start: bug.bz_id }
    end
    @res = result.to_json
    respond_to do |format|
      format.json { render json: @res }
    end
  end

  # FIXME: Use polisher to compare the Gemfile against Fedora
  def gemfile_tool
    if params[:gemfile]

      @gemfile = params[:gemfile]
      @gemfile = @gemfile.read unless @gemfile.is_a?(String)

      @gemfile.gsub!(/\r*/, '')

      is_lock = !@gemfile.scan(/\nGEM\n/).empty?
      is_lock = !@gemfile.scan(/\nPLATFORMS\n/).empty?    unless is_lock
      is_lock = !@gemfile.scan(/\nDEPENDENCIES\n/).empty? unless is_lock

      lines = @gemfile.split "\n"

      dependencies = []
      @result = []

      if !is_lock
        lines.each do |line|
          if line =~ /^gem\s+'([^']*)'$/
            # gem name only
            dependencies << { name: Regexp.last_match[1], version: nil }

          elsif line =~ /^gem\s+'([^']*)',\s*'([^']*)'.*$/
            # gem with possible version
            name = Regexp.last_match[1]
            version = nil
            begin
              version = Versionomy.parse(Regexp.last_match[2].split.last)
            rescue Versionomy::Errors::ParseError
            end
            dependencies << { name: name, version: version }

            # else # ignore
          end
        end
      else
        lines.each do |line|
          if line =~ /^\s*([^\s]*)\s*\(([^\)]*)\)$/
            # gem name / version
            name, version = Regexp.last_match[1], Regexp.last_match[2]
            begin
              version = Versionomy.parse(version.split.last)
            rescue Versionomy::Errors::ParseError
            end
            dependencies << { name: name, version: version }
          end
        end
      end

      dependencies.each do |dep|
        unless @result.find { |res| res[:name] == dep[:name] }
          dep_fully_satisfied = true
          rpm = FedoraRpm.find_by_name('rubygem-' + dep[:name])
          if !rpm
            dep_fully_satisfied = false
            @result << { name: dep[:name], success: false, message: _('%{dep_name} not found in Fedora') % { dep_name: dep[:name] } }

          elsif !dep[:version].nil?
            rpm.rpm_versions.each do |rv|
              unless rv.rpm_version.nil?
                if Versionomy.parse(rv.rpm_version) < dep[:version]
                  dep_fully_satisfied = false
                  @result << { name: dep[:name], success: false, message: _('%{dep_name} (%{dep_version}) is too old in %{rv_fedora_version} (which has %{rv_rpm_version})') % { dep_name: dep[:name], dep_version: dep[:version], rv_fedora_version: rv.fedora_version, rv_rpm_version: rv.rpm_version } }

                else
                  @result << { name: dep[:name], success: true, message: _('%{dep_name} (%{dep_version}) is sufficient in %{rv_fedora_version}') % { dep_name: dep[:name], dep_version: dep[:version], rv_fedora_version: rv.fedora_version } }
                end
              end
            end
          end

          if dep_fully_satisfied
            @result << { name: dep[:name], success: true, message: _('%{dep_name} is in Fedora!') % { dep_name: dep[:name] } }
          end
        end
      end
    end
  end
end

app/views/stats/_popular_gems.html.haml
%div.stats.well
  %h2
    = _('Popular gems')
  %table.table.table-striped.table-condensed
    %thead
      %tr
        %th
          = _('Gem')
        %th
          = _('Version')
        %th
          = _('Rpm Version')
        %th
          = _('Downloads')
    %tbody
      - @popular_gems.each do |gem|
        %tr
          %td= link_to gem.name, rubygem_path(gem.name)
          %td= gem.version
          %td= gem.version_in_fedora('Rawhide')
          %td= number_with_delimiter(gem.downloads)

app/views/stats/_recent_rpms.html.haml
%div.stats.well
  %h2
    = _('Recently updated rpms')
  %table.table.table-striped.table-condensed
    %thead
      %tr
        %th
          = _('Rpm')
        %th
          = _('Upstream')
        %th
          = _('Rawhide')
        %th
          = _('Last Commit')
    %tbody
      - @recent_rpms.each do |rpm|
        %tr
          %td= link_to rpm.shortname, fedorarpm_path(rpm.name)
          %td= rpm.ruby_gem.version if rpm.ruby_gem
          %td= rpm.version_for 'Rawhide'
          %td= rpm.last_commit_date_in_words

app/views/stats/gemfile_tool.html.haml
-if @result
  %h3
    = link_to _('Back'), gemfile_tool_stats_path
  - @result.each do |res|
    %span{:class => res[:success] ? 'gemfile_tool_result_success' : 'gemfile_tool_result_fail'}
      = res[:message]

-else
  %h2
    = _('Test your Gemfile or Gemfile.lock against Fedora')
  %h2
    = _('Upload it')
  %div{:style => 'clear: both'}
  .gemfile_input_container
    %form{:method => :post, :action => :gemfile_tool, :enctype => 'multipart/form-data'}
      %input{:type => :file, :id => 'gemfile', :name => 'gemfile'}
      %br
      %input{:type => :submit, :value => _('upload')}


  %h2
    = _('or Paste it')
  .gemfile_input_container
    %form{:method => :post, :action => :gemfile_tool}
      %textarea{:id => 'gemfile', :name => 'gemfile', :rows => 50}
      %br
      %input{:type => :submit, :value => _("submit")}
  %div{:style => 'clear: both'}

app/views/stats/timeline.html.haml
:css
  div.timeline-frame {
      border: 1px solid #BEBEBE;
      overflow: hidden;
  }

  div.timeline-axis {
      border-color: #BEBEBE;
      border-width: 1px;
      border-top-style: solid;
  }
  div.timeline-axis-grid {
      border-left-style: solid;
      border-width: 1px;
  }
  div.timeline-axis-grid-minor {
      border-color: #e5e5e5;
  }
  div.timeline-axis-grid-major {
      border-color: #bfbfbf;
  }
  div.timeline-axis-text {
      color: #4D4D4D;
      padding: 3px;
      white-space: nowrap;
  }

  div.timeline-axis-text-minor {
  }

  div.timeline-axis-text-major {
  }

  div.timeline-event {
      color: #1A1A1A;
      border-color: #97B0F8;
      background-color: #D5DDF6;


      display: inline-block;

  }

  div.timeline-event-selected {
      border-color: #FFC200;
      background-color: #FFF785;
      z-index: 999;
  }


  div.timeline-event-box {
      text-align: center;
      border-style: solid;
      border-width: 1px;
      border-radius: 5px;
      -moz-border-radius: 5px; /* For Firefox 3.6 and older */
  }

  div.timeline-event-dot {
      border-style: solid;
      border-width: 5px;
      border-radius: 5px;
      -moz-border-radius: 5px;  /* For Firefox 3.6 and older */
  }

  div.timeline-event-range {
      border-style: solid;
      border-width: 1px;
      border-radius: 2px;
      -moz-border-radius: 2px;  /* For Firefox 3.6 and older */
  }

  div.timeline-event-range-drag-left {
      cursor: w-resize;
      z-index: 1000;
  }

  div.timeline-event-range-drag-right {
      cursor: e-resize;
      z-index: 1000;
  }


  div.timeline-event-line {
      border-left-width: 1px;
      border-left-style: solid;
  }

  div.timeline-event-content {
      margin: 5px;
      white-space: nowrap;
      overflow: hidden;
  }

  div.timeline-groups-axis {
      border-color: #BEBEBE;
      border-width: 1px;
  }
  div.timeline-groups-text {
      color: #4D4D4D;
      padding-left: 10px;
      padding-right: 10px;
  }

  div.timeline-currenttime {
      background-color: #FF7F6E;
      width: 2px;
  }

  div.timeline-customtime {
      background-color: #6E94FF;
      width: 2px;
      cursor: move;
  }

  div.timeline-navigation {
      font-family: arial;
      font-size: 20px;
      font-weight: bold;
      color: gray;

      border: 1px solid #BEBEBE;
      background-color: #F5F5F5;
      border-radius: 2px;
      -moz-border-radius: 2px;  /* For Firefox 3.6 and older */
  }

  div.timeline-navigation-new, div.timeline-navigation-delete,
  div.timeline-navigation-zoom-in,  div.timeline-navigation-zoom-out,
  div.timeline-navigation-move-left, div.timeline-navigation-move-right {
      cursor: pointer;
      padding: 10px 10px;
      float: left;
      text-decoration: none;
      border-color: #BEBEBE; /* border is used for the separator between new and navigation buttons */

      width: 16px;
      height: 16px;
  }

  div.timeline-navigation-new {
      background: url('img/16/new.png') no-repeat center;
  }

  div.timeline-navigation-delete {
      padding: 0px;
      padding-left: 5px;
      background: url('img/16/delete.png') no-repeat center;
  }

  div.timeline-navigation-zoom-in {
      background: url('img/16/zoomin.png') no-repeat center;
  }

  div.timeline-navigation-zoom-out {
      background: url('img/16/zoomout.png') no-repeat center;
  }

  div.timeline-navigation-move-left {
      background: url('img/16/moveleft.png') no-repeat center;
  }

  div.timeline-navigation-move-right {
      background: url('img/16/moveright.png') no-repeat center;
  }

:javascript
  function render_timeline() {
    var timeline;

    $.getJSON("tljson.json",function(result){
      drawVisualization(result);
    });

    function drawVisualization(result) {
      var options = {
                    'width':  '100%',
                    'height': '400px',
                    'editable': false,
                    'style': 'box',
                    'showMajorLabels': false,
                    'showMinorLabels': false
      };

      timeline = new links.Timeline(document.getElementById('mytimeline'));
      timeline.draw(result, options);
    };
  }

%body{:onload => "render_timeline();"}
  %h1= _('Timeline (Bugs and Versions)')
  %p{:style => "text-align:center;"}
    = _('This timeline depicts a chronological visualization of the bugs & version releases for %{gem_name}') % { :gem_name => @stat_id }
  #mytimeline

app/views/stats/user_rpms.html.haml
.d3_chart_container
  %h1= _('Bubble Chart:')
  %h2= _('This graph shows the packages, which are represented by circles, that the user %{user_name} owns.') % { :user_name => @name }
  %h2= _('The size of each circle is proportional to the number of commits for that package.')
  #chart

:javascript
  var r = 700
    color = d3.scale.category20c();
  var bubble_layout = d3.layout.pack()
      .size([r,r])
      .sort(null)
      .padding(1.5);

  var vis = d3.select("#chart").append("svg")
      .attr("width" , r)
      .attr("height", r)

  var array = #{@rpms_json}

  arr = [];
  for (i = 0; i < array.length; i++)
  {
    arr[i] = { "name": array[i]["name"].split("rubygem-")[1], "value": array[i]["commits"]}
  }

  var selection = vis.selectAll("g.node")
                .data(bubble_layout.nodes({children: arr}).filter(function(d) { return !d.children; }) );
  //Enter
  var tooltip = d3.select("body")
    .append("div")
    .style("position", "absolute")
    .style("z-index", "10")
    .style("background-color", "white")
    .style("width", "200px")
    .style("padding-top", "10px")
    .style("padding-bottom", "10px")
    .style("text-align", "center")
    .style("border-radius", "15px")
    .style("-moz-border-radius", "15px")
    .style("-webkit-border-radius", "15px")
    .style("border-style", "solid")
    .style("border-width", "2px")
    .style("visibility", "hidden")

  posX = null;
  posY = null;
  document.onmousemove = function(evt) {
    if (typeof evt == 'undefined') {
      myEvent = window.event;
    }
    else {
      myEvent = evt;
    }
    posX = myEvent.pageX+10;
    posY = myEvent.pageY;
    tooltip.style("top", posY+"px").style("left", posX+"px")
  }
  node = selection.enter().append("g")
                .attr("class", "node")
                .attr("transform", function(d) { return "translate(" + d.x + ", " + d.y + ")"; });
  node.append("circle")
      .attr("r", function(d) { return d.r; })
      .on("click", function(d, i) { window.location = '/fedorarpms/rubygem-' + d.name; })
      .on("mouseover", function(d){document.body.style.cursor = "pointer"; tooltip.style("visibility", "visible"); tooltip.html("RubyGem Name: "+d.name+ "<br>Commits: " + d.value +"<br>Click for more info...");})
      .on("mouseout", function(){document.body.style.cursor = "default";  tooltip.style("visibility", "hidden");})
      .style("fill", function(d) { return color(d.name); });

  node.append("text")
      .on("click", function(d, i) { window.location = '/fedorarpms/rubygem-' + d.name; })
      .on("mouseover", function(){document.body.style.cursor = "pointer"; tooltip.style("visibility", "visible");})
      .on("mouseout", function(){document.body.style.cursor = "default";  tooltip.style("visibility", "hidden");})
      .attr("text-anchor", "middle")
      .attr("dy", ".3em")
      .style("font-color", "FFF")
      .text(function(d) { return d.name.substring(0, d.r/3); });