config/routes.rb
Isitfedoraruby::Application.routes.draw do

  root to: 'home#show'

  get 'contribute', to: 'static_pages#contribute'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'

  get 'searches/suggest_gems' => 'searches#suggest_gems'
  post 'searches/' => 'searches#redirect'
  get 'searches/:id' => 'searches#index'

  resources :fedorarpms, only: [:index, :show] do
    member do
      get :full_deps
      get :full_dependencies
      get :full_dependents
      get :by_owner
      get :badge
      get :not_found
    end
  end

  resources :rubygems, only: [:index, :show]

  resources :stats, only: [:index] do
    get :gemfile_tool, on: :collection
    get :user_rpms
    get :timeline
    get :tljson
    get :user_rpms_data
    post :gemfile_tool, on: :collection
  end

  # unless Rails.application.config.consider_all_requests_local
  get '*not_found', to: 'errors#error_404'
  #  end

end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    Version
    = Git::VERSION
    @
  %small
    = link_to Git::REVISION,
      "https://github.com/axilleas/isitfedoraruby/commit/#{Git::REVISION}"
  %nav
    %ul
      %li= link_to _('Contact'), contact_path

app/views/layouts/_header.html.haml
%div.container
  %nav.navbar.navbar-default.navbar-fixed-top{:role => 'navigation'}
    %div.navbar-header
      = link_to 'FedoraRuby', root_path, class: 'navbar-brand'
    %ul.nav.navbar-nav
      %li= link_to _('Home'), root_path
      %li= link_to _('Ruby Gems'), rubygems_path
      %li= link_to _('Fedora Rpms'), fedorarpms_path
      %li= link_to _('Contribute'), contribute_path
      %li= link_to _('About'), about_path
      %li
        = form_tag( { :controller => 'searches', :action => 'redirect' },
        :class => 'navbar-form', :method => 'post') do
          %div.form-group
            = text_field_tag :search, params[:search] ||= '', id: 'search_field',
              class: 'search-query form-control', placeholder: 'Search'
          = submit_tag _('Search'), name: nil, class: 'btn btn-default'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Isitfedoraruby</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= "isitFedoraRuby - #{@page_title}"
    = stylesheet_link_tag "application", :media => "all"
    -#= stylesheet_link_tag "d3-cluster", :media => "all"
    = javascript_include_tag "application"
    -#= javascript_include_tag "d3.v2.js"
    -#= javascript_include_tag "timeline-min.js"
    -#= javascript_include_tag "typeahead.bundle.js"
    = csrf_meta_tags

  %body
    = render 'layouts/header'
    %div.container
      = yield
      = render 'layouts/footer'